// This file is generated by Velite

import type { collections } from 'mdxld'

type Collections = typeof collections

export type mdx = Collections['mdx']['schema']['_output']
export declare const mdx: mdx[]
