// This file is generated by Velite

import type __vc from '../.velite.temp.js'

type Collections = typeof __vc.collections

export type mdx = Collections['mdx']['schema']['_output']
export declare const mdx: mdx[]
