export const horizontalRoles = [
  "Executive",
  "Finance Executive",
  "Founder",
  "Human Resources Executive",
  "Information Technology Executive",
  "Legal Executive",
  "Marketing Executive",
  "Medical & Health Executive",
  "Operations Executive",
  "Sales Leader",
  "Product Development",
  "Product Management",
  "Artificial Intelligence / Machine Learning",
  "Bioengineering",
  "Biometrics",
  "Business Intelligence",
  "Chemical Engineering",
  "Cloud / Mobility",
  "Data Science",
  "DevOps",
  "Digital Transformation",
  "Emerging Technology / Innovation",
  "Engineering & Technical",
  "Industrial Engineering",
  "Mechanic",
  "Mobile Development",
  "Project Management",
  "Research & Development",
  "Scrum Master / Agile Coach",
  "Software Development",
  "Support / Technical Services",
  "Technician",
  "Technology Operations",
  "Test / Quality Assurance",
  "UI / UX",
  "Web Development",
  "All Design",
  "Product or UI/UX Design",
  "Graphic / Visual / Brand Design",
  "Teacher",
  "Principal",
  "Superintendent",
  "Professor",
  "Accounting",
  "Finance",
  "Financial Planning & Analysis",
  "Financial Reporting",
  "Financial Strategy",
  "Financial Systems",
  "Internal Audit & Control",
  "Investor Relations",
  "Mergers & Acquisitions",
  "Real Estate Finance",
  "Financial Risk",
  "Shared Services",
  "Sourcing / Procurement",
  "Tax",
  "Treasury",
  "Compensation & Benefits",
  "Culture, Diversity & Inclusion",
  "Employee & Labor Relations",
  "Health & Safety",
  "Human Resource Information System",
  "Human Resources",
  "HR Business Partner",
  "Learning & Development",
  "Organizational Development",
  "Recruiting & Talent Acquisition",
  "Talent Management",
  "Workforce Management",
  "People Operations",
  "Application Development",
  "Business Service Management / ITSM",
  "Collaboration & Web App",
  "Data Center",
  "Data Warehouse",
  "Database Administration",
  "eCommerce Development",
  "Enterprise Architecture",
  "Help Desk / Desktop Services",
  "HR / Financial / ERP Systems",
  "Information Security",
  "Information Technology",
  "Infrastructure",
  "IT Asset Management",
  "IT Audit / IT Compliance",
  "IT Operations",
  "IT Procurement",
  "IT Strategy",
  "IT Training",
  "Networking",
  "Project & Program Management",
  "Quality Assurance",
  "Retail / Store Systems",
  "Servers",
  "Storage & Disaster Recovery",
  "Telecommunications",
  "Virtualization",
  "Acquisitions",
  "Compliance",
  "Contracts",
  "Corporate Secretary",
  "eDiscovery",
  "Ethics",
  "Governance",
  "Governmental Affairs & Regulatory Law",
  "Intellectual Property & Patent",
  "Labor & Employment",
  "Lawyer / Attorney",
  "Legal",
  "Legal Counsel",
  "Legal Operations",
  "Litigation",
  "Privacy",
  "Advertising",
  "Brand Management",
  "Content Marketing",
  "Customer Experience",
  "Customer Marketing",
  "Demand Generation",
  "Digital Marketing",
  "eCommerce Marketing",
  "Event Marketing",
  "Field Marketing",
  "Lead Generation",
  "Marketing",
  "Marketing Analytics / Insights",
  "Marketing Communications",
  "Marketing Operations",
  "Product Marketing",
  "Public Relations",
  "Search Engine Optimization / Pay Per Click",
  "Social Media Marketing",
  "Strategic Communications",
  "Technical Marketing",
  "Anesthesiology",
  "Chiropractics",
  "Clinical Systems",
  "Dentistry",
  "Dermatology",
  "Doctors / Physicians",
  "Epidemiology",
  "First Responder",
  "Infectious Disease",
  "Medical Administration",
  "Medical Education & Training",
  "Medical Research",
  "Medicine",
  "Neurology",
  "Nursing",
  "Nutrition & Dietetics",
  "Obstetrics / Gynecology",
  "Oncology",
  "Opthalmology",
  "Optometry",
  "Orthopedics",
  "Pathology",
  "Pediatrics",
  "Pharmacy",
  "Physical Therapy",
  "Psychiatry",
  "Psychology",
  "Public Health",
  "Radiology",
  "Social Work",
  "Call Center",
  "Construction",
  "Corporate Strategy",
  "Customer Service / Support",
  "Enterprise Resource Planning",
  "Facilities Management",
  "Leasing",
  "Logistics",
  "Office Operations",
  "Operations",
  "Physical Security",
  "Project Development",
  "Quality Management",
  "Real Estate",
  "Safety",
  "Store Operations",
  "Supply Chain",
  "Account Management",
  "Business Development",
  "Channel Sales",
  "Customer Retention & Development",
  "Customer Success",
  "Field / Outside Sales",
  "Inside Sales",
  "Partnerships",
  "Revenue Operations",
  "Sales",
  "Sales Enablement",
  "Sales Engineering",
  "Sales Operations",
  "Sales Training",
  "Consultant",
]