export const industries = [
  "apparel & fashion",
  "automotive",
  "civic & social organization",
  "consumer services",
  "food & beverages",
  "information technology & services",
  "investment banking",
  "nanotechnology",
  "oil & energy",
  "ranching",
  "utilities",
  "warehousing",
  "defense & space",
  "financial services",
  "higher education",
  "restaurants",
  "semiconductors",
  "wine & spirits",
  "computer hardware",
  "hospital & health care",
  "libraries",
  "outsourcing/offshoring",
  "philanthropy",
  "transportation/trucking/railroad",
  "logistics & supply chain",
  "management consulting",
  "marketing & advertising",
  "design",
  "education management",
  "individual & family services",
  "professional training & coaching",
  "venture capital & private equity",
  "capital markets",
  "airlines/aviation",
  "legislative office",
  "food production",
  "market research",
  "paper & forest products",
  "photography",
  "program development",
  "railroad manufacture",
  "agriculture",
  "broadcast media",
  "gambling & casinos",
  "hospitality",
  "investment management",
  "supermarkets",
  "chemicals",
  "computer games",
  "graphic design",
  "industrial automation",
  "publishing",
  "real estate",
  "telecommunications",
  "think tanks",
  "computer software",
  "import & export",
  "pharmaceuticals",
  "public policy",
  "translation & localization",
  "architecture & planning",
  "e-learning",
  "electrical/electronic manufacturing",
  "insurance",
  "law enforcement",
  "retail",
  "aviation & aerospace",
  "fishery",
  "plastics",
  "printing",
  "public relations & communications",
  "law practice",
  "package/freight delivery",
  "packaging & containers",
  "alternative dispute resolution",
  "leisure, travel & tourism",
  "computer networking",
  "consumer electronics",
  "facilities services",
  "furniture",
  "internet",
  "renewables & environment",
  "building materials",
  "events services",
  "legal services",
  "medical practice",
  "motion pictures & film",
  "public safety",
  "tobacco",
  "arts & crafts",
  "commercial real estate",
  "health, wellness & fitness",
  "human resources",
  "shipbuilding",
  "veterinary",
  "wireless",
  "dairy",
  "fund-raising",
  "nonprofit organization management",
  "staffing & recruiting",
  "civil engineering",
  "environmental services",
  "executive office",
  "wholesale",
  "accounting",
  "museums & institutions",
  "writing & editing",
  "business supplies & equipment",
  "fine art",
  "government relations",
  "machinery",
  "maritime",
  "mining & metals",
  "newspapers",
  "information services",
  "international affairs",
  "luxury goods & jewelry",
  "mental health care",
  "performing arts",
  "security & investigations",
  "sports",
  "cosmetics",
  "glass, ceramics & concrete",
  "mechanical or industrial engineering",
  "primary/secondary education",
  "research",
  "government administration",
  "media production",
  "online media",
  "religious institutions",
  "textiles",
  "construction",
  "international trade & development",
  "music",
  "banking",
  "computer & network security",
  "consumer goods",
  "entertainment",
  "farming",
  "medical devices",
  "military",
  "recreational facilities & services",
  "alternative medicine",
  "animation",
  "biotechnology",
  "judiciary",
  "political organization",
  "sporting goods",
]